### ISSUE TITLE
Faker parameter resolution: Allow to resolve nested parameter definition

### ISSUE THREAD

**Issue by shulard** [CHStudio/Raven#18]
**Describe the bug**

When you define a "faker resolvable" property, you can't have more than one level of faker resolution.

For example with somethink link that: `'<storageIdFromAet(<dicomAet("WS-PARIS")>)>'`, `dicomAet` will not be called.

**To Reproduce**

A sample YAML configuration to generate a request with that kind of issue:

```yaml
testThatCase:
  uri:
    base: /api/uri?parameter={storage}
    parameters:
      '{storage}': '<storageIdFromAet(<dicomAet("WS-PARIS")>)>'
```

**Expected behavior**

We might allow to resolve nested faker definition.
