### ISSUE TITLE
Use methods in response expectations

### ISSUE THREAD

**Issue by schcsaba** [CHStudio/Raven#27]
In certain cases, for example, if we want to verify an id or a date generated by a fixture, it would be useful to have the possibility of using methods in the response expectations the same way as in the request uri parameters or in the request body. 

In this request, defined in a yaml file, I would like to expect an id in the response, but it's not possible at present:

```yaml
requests:
  Success (200):
    uri:
      base: /api/institutions/agreement-templates/{agreementTemplate}
      parameters:
        '{agreementTemplate}': '<agreementTemplateUid("Agreement Template Ronald Reagan UCLA Medical Center", ["HU"])>'
    method: PUT
    headers:
      <<: *headers
    body:
      uid: '<agreementTemplateUid("Agreement Template Ronald Reagan UCLA Medical Center", ["HU"])>'
      name: MyAgreementTemplate
      file: '<mediaIdFromName("file-not-taken.pdf")>'
      filename: file-not-taken.pdf
      geographicalRestrictions:
        - FR
        - US
    statusCode: 200
    valuesNeedsToMatch:
 # This is not possible -> "[data][attributes][uid]":  '<agreementTemplateUid("Agreement Template Ronald Reagan UCLA Medical Center", ["HU"])>'
      "[data][attributes][name]": MyAgreementTemplate
      "[data][attributes][filename]": file-not-taken.pdf
      "[data][attributes][geographicalRestrictions]":
        - FR
        - US
      "[data][relationships][media][data][attributes][name]": file-not-taken.pdf
```

I was not able to come up with an alternative solution. I use static values in the fixtures or I just leave out dynamic values from the response expectations.
